version: 2

sources:
  - name: django
    schema: staging_django
    tables:
      - name: orgs
        identifier: ddpui_org
      - name: orgusers
        identifier: ddpui_orguser
      - name: users
        identifier: auth_user
      - name: roles
        identifier: ddpui_role
      - name: dataflows
        identifier: ddpui_orgdataflowv1
      - name: orgtasks
        identifier: ddpui_orgtask
      - name: orgplans
        identifier: ddpui_orgplans
  
  - name: prefect
    schema: staging_prefect
    tables:
      - name: deployment
        identifier: deployment
      - name: flow_run
        identifier: flow_run
      - name: work_pool
        identifier: work_pool
      - name: work_queue
        identifier: work_queue
      - name: deployment_schedule
        identifier: deployment_schedule
      - name: task_run
        identifier: task_run

  - name: airbyte
    schema: staging_airbyte
    tables:
      - name: jobs
        identifier: jobs
      - name: attempts
        identifier: attempts
      - name: actor
        identifier: actor
      - name: actor_definition
        identifier: actor_definition
      - name: actor_definition_version
        identifier: actor_definition_version
      - name: scoped_configuration
        identifier: scoped_configuration